version: "3.7"

services:
  database:
    image: postgres
    restart: always
    env_file: .env
#    environment:
#      POSTGRES_DB: contact_book_db
#      POSTGRES_USER: sprow
#      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: